version: "3.1"

services:
    postgres:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - postgres-network

    app-reader:
        build: .
        user: node
        container_name: reader_api
        tty: true
        stdin_open: true
        command: npm start
        image: reader-api
        restart: always
        volumes:
            - ./src:/app/src
        depends_on:
            - postgres
        ports:
            - 3000:3000
        environment:
            DATABASE_NAME: postgres
            DATABASE_USER: postgres
            DATABASE_PASSWORD: postgres
            DATABASE_HOST: postgres
            DATABASE_PORT: 5432
        networks:
            - postgres-network

volumes:
    postgres:

networks:
    postgres-network:
        driver: bridge
